[package]
name = "modern-ens-rennes-presentation"
version = "0.1.0"
compiler = "0.13.0"
entrypoint = "theme.typ"
authors = ["Zacharie <@zacharie-moughanim>", "Malo <@MDLC01>"]
license = "MIT"
description = "Unofficial ENS Rennes slides."
repository = "https://github.com/zacharie-moughanim/modern-ens-rennes-presentation"
categories = ["presentation"]
keywords = ["École Normale Supérieure de Rennes", "ENS Rennes", "presentation", "slides"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
